### ISSUE TITLE
Implement API pagination through PageableManagerInterface

### ISSUE THREAD

**Issue by plouc** [sonata-project/SonataCoreBundle#58]
#### UserBundle
- [x] Sonata\UserBundle\Model\UserManagerInterface - sonata-project/SonataUserBundle#398
- [x] Sonata\UserBundle\Model\GroupManagerInterface
#### PageBundle
- [x] Sonata\PageBundle\Model\PageManagerInterface - sonata-project/SonataPageBundle#327
- [x] Sonata\PageBundle\Model\SiteManagerInterface - sonata-project/SonataPageBundle#327
- [x] Sonata\PageBundle\Model\SnapshotManagerInterface ?
#### ClassificationBundle
- [x] Sonata\ClassificationBundle\Model\TagManagerInterface - sonata-project/SonataClassificationBundle#36
- [x] Sonata\ClassificationBundle\Model\CategoryManagerInterface - sonata-project/SonataClassificationBundle#36
- [x] Sonata\ClassificationBundle\Model\CollectionManagerInterface - sonata-project/SonataClassificationBundle#36
#### E-commerce
- [x] Sonata\Component\Product\ProductManagerInterface - sonata-project/ecommerce#241
- [x] Customer
- [x] Basket
- [x] Invoice
- [x] Order
#### NewsBundle
- [x] Sonata\NewsBundle\Model\PostManagerInterface - sonata-project/SonataNewsBundle#192
- [x] Sonata\NewsBundle\Model\CommentManagerInterface - sonata-project/SonataNewsBundle#196

**Comment by amine26tz** [comment]
@plouc, the GroupManager pager was implemented in sonata-project/SonataUserBundle/pull/506

**Comment by bdejacobet** [comment]
@plouc 
Pager was implemented in E-commerce
* Customer sonata-project/ecommerce#294 
* Basket sonata-project/ecommerce#295
* Invoice sonata-project/ecommerce#296
* Order sonata-project/ecommerce#297

**Comment by bdejacobet** [comment]
@plouc 
An other PR to throw an exception when a wrong sort field passed in API basket and API customer sonata-project/ecommerce#300

**Comment by jordisala1991** [comment]
This is already implemented on all bundles mentioned. Closing
