### ISSUE TITLE
Replace by form- and twig- extensions

### ISSUE THREAD

**Issue by wbloszyk** [sonata-project/SonataCoreBundle#740]
CoreBundle should not be used with any Sonata 4 bundles. To do it and keep BC i split upgrade to steps:
1. upgrade CoreBundle to newest version (with form- and twig- extensions)
1. drop deprecations from CoreBundle
1. delete CoreBundle
1. drop deprecations from extensions 0.x
1. upgrade extensions to 1.x

I'm not sure about using 1.x extensions with type hints but we can remove them in 1.x and release 2.x with them. 

## Todo
- [ ] #739 - Prepare to replace by form- and twig- extensions
- [ ] drop CoreBundle depencencies in Sonata 3
    - [ ] require extensions 0.x || 1.x instead
    - [ ] registerFormMapping if (class_exists(FormHelper) 
    - [ ] replace CoreBundle by extensions API
        - we can do it becousethey are aliases
        - [ ] CoreBundle\Form\Validator\ErrorElement by Sonata\Form\Validator\ErrorElement
        - [ ] CoreBundle\Form\Validator\InlineValidator by Sonata\Form\Validator\InlineValidator
        - ....
    - [ ] remove other dependencies

**Comment by wbloszyk** [comment]
## Sonata 3 sandbox without CoreBundle
```
sonata-project/admin-bundle              dev-drop_core_in_3 349ea44 dev-drop_core_in_3 349ea44 The missing Symfony Admin Generator
sonata-project/block-bundle              dev-drop_core_in_3 128436c dev-drop_core_in_3 128436c Symfony SonataBlockBundle
sonata-project/cache                     1.1.1                      2.0.1                      Cache library
sonata-project/cache-bundle              2.4.2                      3.2.1                      This bundle provides caching services
sonata-project/classification-bundle     dev-drop_core_in_3 d16dfa6 dev-drop_core_in_3 d16dfa6 Symfony SonataClassificationBundle
sonata-project/comment-bundle            dev-drop_core_in_3 ea83d80 dev-drop_core_in_3 ea83d80 Integrate the FOSCommentBundle in the Sonata Project
sonata-project/datagrid-bundle           2.5.0                      3.2.0                      Symfony SonataDatagridBundle
sonata-project/doctrine-extensions       1.6.0                      1.6.0                      Doctrine2 behavioral extensions
sonata-project/doctrine-orm-admin-bundle dev-drop_core_in_3 8eaebfc dev-drop_core_in_3 8eaebfc Symfony Sonata / Integrate Doctrine ORM into the SonataAdminBundle
sonata-project/easy-extends-bundle       2.5.0                      2.5.0                      Symfony SonataEasyExtendsBundle
sonata-project/ecommerce                 dev-drop_core_in_3 5baeb1e dev-drop_core_in_3 5baeb1e E-Commerce solution provided by Sonata
sonata-project/exporter                  1.11.1                     2.2.0                      Lightweight Exporter library
sonata-project/form-extensions           0.x-dev c51c2b0            dev-master 91c32b5         Symfony form extensions
sonata-project/formatter-bundle          dev-drop_core_in_3 5e1c62d dev-drop_core_in_3 5e1c62d Symfony SonataFormatterBundle
sonata-project/google-authenticator      2.2.0                      2.2.0                      Library to integrate Google Authenticator into a PHP project
sonata-project/intl-bundle               2.7.0                      2.7.0                      Symfony SonataIntlBundle
sonata-project/media-bundle              dev-drop_core_in_3 64cc053 dev-drop_core_in_3 64cc053 Symfony SonataMediaBundle
sonata-project/news-bundle               dev-drop_core_in_3 5e99564 dev-drop_core_in_3 5e99564 Symfony SonataNewsBundle
sonata-project/notification-bundle       dev-drop_core_in_3 c18ae80 dev-drop_core_in_3 c18ae80 Symfony SonataNotificationBundle
sonata-project/page-bundle               dev-drop_core_in_3 b2f4c0e dev-drop_core_in_3 b2f4c0e This bundle provides a Site and Page management through container and block services
sonata-project/seo-bundle                dev-drop_core_in_3 652bed8 dev-drop_core_in_3 652bed8 Symfony SonataSeoBundle
sonata-project/timeline-bundle           dev-drop_core_in_3 b2c660a dev-drop_core_in_3 b2c660a Integrates SpyTimelineBundle into Sonata
sonata-project/twig-extensions           0.x-dev 01c461f            dev-master 0c0a6bc         Sonata twig extensions
sonata-project/user-bundle               dev-drop_core_in_3 360a0d7 dev-drop_core_in_3 360a0d7 Symfony SonataUserBundle
```

## Sonata 3 sandbox with CoreBundle
```
sonata-project/admin-bundle              dev-drop_core_in_3 349ea44 dev-drop_core_in_3 349ea44 The missing Symfony Admin Generator
sonata-project/block-bundle              dev-drop_core_in_3 128436c dev-drop_core_in_3 128436c Symfony SonataBlockBundle
sonata-project/cache                     1.1.1                      2.0.1                      Cache library
sonata-project/cache-bundle              2.4.2                      3.2.1                      This bundle provides caching services
sonata-project/classification-bundle     dev-drop_core_in_3 d16dfa6 dev-drop_core_in_3 d16dfa6 Symfony SonataClassificationBundle
sonata-project/comment-bundle            dev-drop_core_in_3 ea83d80 dev-drop_core_in_3 ea83d80 Integrate the FOSCommentBundle in the Sonata Project
sonata-project/core-bundle               3.x-dev 65a57fe            dev-master 5290847         Symfony SonataCoreBundle (abandoned)
sonata-project/datagrid-bundle           2.5.0                      3.2.0                      Symfony SonataDatagridBundle
sonata-project/doctrine-extensions       1.6.0                      1.6.0                      Doctrine2 behavioral extensions
sonata-project/doctrine-orm-admin-bundle dev-drop_core_in_3 8eaebfc dev-drop_core_in_3 8eaebfc Symfony Sonata / Integrate Doctrine ORM into the SonataAdminBundle
sonata-project/easy-extends-bundle       2.5.0                      2.5.0                      Symfony SonataEasyExtendsBundle
sonata-project/ecommerce                 dev-drop_core_in_3 5baeb1e dev-drop_core_in_3 5baeb1e E-Commerce solution provided by Sonata
sonata-project/exporter                  1.11.1                     2.2.0                      Lightweight Exporter library
sonata-project/form-extensions           0.x-dev c51c2b0            dev-master 91c32b5         Symfony form extensions
sonata-project/formatter-bundle          dev-drop_core_in_3 5e1c62d dev-drop_core_in_3 5e1c62d Symfony SonataFormatterBundle
sonata-project/google-authenticator      2.2.0                      2.2.0                      Library to integrate Google Authenticator into a PHP project
sonata-project/intl-bundle               2.7.0                      2.7.0                      Symfony SonataIntlBundle
sonata-project/media-bundle              dev-drop_core_in_3 64cc053 dev-drop_core_in_3 64cc053 Symfony SonataMediaBundle
sonata-project/news-bundle               dev-drop_core_in_3 5e99564 dev-drop_core_in_3 5e99564 Symfony SonataNewsBundle
sonata-project/notification-bundle       dev-drop_core_in_3 c18ae80 dev-drop_core_in_3 c18ae80 Symfony SonataNotificationBundle
sonata-project/page-bundle               dev-drop_core_in_3 b2f4c0e dev-drop_core_in_3 b2f4c0e This bundle provides a Site and Page management through container and block services
sonata-project/seo-bundle                dev-drop_core_in_3 652bed8 dev-drop_core_in_3 652bed8 Symfony SonataSeoBundle
sonata-project/timeline-bundle           dev-drop_core_in_3 b2c660a dev-drop_core_in_3 b2c660a Integrates SpyTimelineBundle into Sonata
sonata-project/twig-extensions           0.x-dev 01c461f            dev-master 0c0a6bc         Sonata twig extensions
sonata-project/user-bundle               dev-drop_core_in_3 360a0d7 dev-drop_core_in_3 360a0d7 Symfony SonataUserBundle
```
